# !without nginx
version: '3'
services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - /tmp/request_logfile.log:/app/request_logfile.log
    restart: on-failure